// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmhcvwiebtdbvyoqrwjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaGN2d2llYnRkYnZ5b3Fyd2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDgzNjIsImV4cCI6MjA2ODQ4NDM2Mn0.vQS627DJRCEWQk6ZdLTz0agCdqoar685KCZbO81MKSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});